openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "API F1"
servers:
  - url: "http://127.0.0.1:3002"

paths:
  /rounds:
    parameters:
      - $ref: "#/components/parameters/roundYear"
    get:
      summary: Obtener las rondas disponibles dado un año
      responses:
        "200":
          description: Las rondas disponibles para el año solicitado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Round"
  /drivers:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
    get:
      summary: Obtener los conductores en una sesión
      responses:
        "200":
          description: "Conductores que participaron de la sesión"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Driver"
        "400":
          description: Alguno de los parámetros es inválido

  /laps:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
      - $ref: "#/components/parameters/driverNumber"
    get:
      summary: Obtener las vueltas que dio un conductor en una sesión
      responses:
        "200":
          description: Vueltas que dio el conductor
          content:
            application/json:
              schema:
                type: object
                properties:
                  lapCount:
                    type: integer
                    description: Cantidad de vueltas
                  fastest_lap:
                    type: integer
                    description: Número de la vuelta que el conductor terminó más rápido (desde 0)
        "400":
          description: Alguno de los parámetros es inválido

  /trajectory:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
      - $ref: "#/components/parameters/driverNumber"
      - $ref: "#/components/parameters/lapNumber"
    get:
      summary: Obtener la trayectoria de un conductor en una vuelta de una sesión
      responses:
        "200":
          description: Trayectoria que siguió el conductor
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cartesian:
                      type: object
                      properties:
                        x:
                          type: number
                          description: Coordenada x de posición
                        y:
                          type: number
                          description: Coordenada y de posición
                        z:
                          type: number
                          description: Coordenada z de posición
                    polar:
                      type: object
                      properties:
                        r:
                          type: number
                          description: Radio de posición
                        theta:
                          type: number
                          description: Ángulo de posición
                        z:
                          type: number
                          description: Coordenada z de posición
                        origin_x:
                          type: number
                          description: Polo coordenada x
                        origin_y:
                          type: number
                          description: Polo coordenada y
                    intrinsic:
                      type: object
                      properties:
                        s:
                          type: number
                          description: Coordenada s de posición (longitud de arco)
                    time:
                      $ref: "#/components/schemas/RelativeTimestamp"
        "400":
          description: Alguno de los parámetros es inválido

  /drifts:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
      - $ref: "#/components/parameters/driverNumber"
      - $ref: "#/components/parameters/lapNumber"
    get:
      description: Obtener los derrapes para un conductor dado, en una vuelta
      responses:
        "200":
          description: Derrapes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      $ref: "#/components/schemas/RelativeTimestamp"
                    x:
                      type: number
                      description: Coordenada x de posición
                    y:
                      type: number
                      description: Coordenada y de posición
                    z:
                      type: number
                      description: Coordenada z de posición
                    drifting:
                      type: number
                      description: Grado de derrape entre 0 (leve) y 1 (fuerte)

        "400":
          description: Alguno de los parámetros es inválido

  /neck_forces:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
      - $ref: "#/components/parameters/driverNumber"
      - $ref: "#/components/parameters/lapNumber"
    get:
      description: Obtener las fuerzas en el cuello de un conductor en una vuelta
      responses:
        "200":
          description: Fuerzas en el cuello del conductor
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      $ref: "#/components/parameters/relativeTimestamp"
                    frontal_neck_force:
                      type: number
                      description: Fuerza frontal en el cuello
                    lateral_neck_force:
                      type: number
                      description: Fuerza lateral en el cuello
                    frontal_g_force:
                      type: number
                      description: Fuerza G frontal
                    lateral_g_force:
                      type: number
                      description: Fuerza G lateral

        "400":
          description: Alguno de los parámetros es inválido

  /kinematics_vectors:
    parameters:
      - $ref: "#/components/parameters/roundYear"
      - $ref: "#/components/parameters/roundNumber"
      - $ref: "#/components/parameters/sessionNumber"
      - $ref: "#/components/parameters/driverNumber"
      - $ref: "#/components/parameters/lapNumber"

    get:
      description: Obtener la velocidad y aceleración de un conductor en una vuelta, a lo largo del tiempo
      responses:
        "200":
          description: Velocidad y aceleración del conductor
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    $ref: "#/components/parameters/relativeTimestamp"
                  velocity:
                    $ref: "#/components/schemas/Velocity"
                  acceleration:
                    $ref: "#/components/schemas/Acceleration"
                  versors:
                    $ref: "#/components/schemas/Versors"

        "400":
          description: Alguno de los parámetros es inválido

components:
  parameters:
    roundYear:
      name: year
      in: query
      schema:
        $ref: "#/components/schemas/RoundYear"
      description: Año de la ronda
    roundNumber:
      name: roundNumber
      in: query
      description: Numero de ronda
      schema:
        $ref: "#/components/schemas/RoundNumber"
    sessionNumber:
      name: sessionNumber
      in: query
      description: Numero de sesión
      schema:
        $ref: "#/components/schemas/SessionNumber"
    driverNumber:
      name: driverNumber
      in: query
      description: Número de conductor
      schema:
        $ref: "#/components/schemas/DriverNumber"
    lapNumber:
      name: lapNumber
      in: query
      description: Número de vuelta
      schema:
        $ref: "#/components/schemas/LapNumber"
    relativeTimestamp:
      name: time
      in: query
      description: "Tiempo, relativo al comienzo de la sesión"
      schema:
        $ref: "#/components/schemas/RelativeTimestamp"

  schemas:
    Round:
      type: object
      properties:
        roundNumber:
          $ref: "#/components/schemas/RoundNumber"
        country:
          type: string
          description: Pais donde se juega la ronda
        location:
          type: string
          description: Ciudad donde se juega la ronda
        eventName:
          type: string
          description: Nombre del evento
        sessions:
          type: array
          description: Sesiones.
          items:
            type: object
            properties:
              sessionNumber:
                $ref: "#/components/schemas/SessionNumber"
              name:
                type: string
                description: >
                  Nombre de la sesión. Ej: "Practice 1", "Qualifying", "Race"
              dateUTC:
                $ref: "#/components/schemas/Timestamp"
    Driver:
      type: object
      properties:
        driverNumber:
          $ref: "#/components/schemas/DriverNumber"
        fullName:
          type: string
          description: Nombre completo del conductor
        countryCode:
          type: string
          format: NED
          description: Código de país de nacionalidad del conductor
        teamName:
          type: string
          description: Nombre del equipo
        teamColor:
          type: string
          format: 3671C6
          description: Color del equipo

    Timestamp:
      type: string
      format: 2022-09-27T18:00:00.000
      description: Fecha y hora

    RelativeTimestamp:
      type: string
      format: 0000-00-00T00:01:00.000
      description: Tiempo, relativo al comienzo de la sesión

    RoundNumber:
      type: integer
      description: Número de ronda
    RoundYear:
      type: integer
      description: Año de la ronda
    SessionNumber:
      type: integer
      description: Número de sesión
    DriverNumber:
      type: integer
      description: Número de conductor
    LapNumber:
      type: integer
      description: Número de vuelta
    Velocity:
      type: object
      description: "Velocidad de un conductor, en coordenadas cartesianas"
      properties:
        vX:
          type: number
        vY:
          type: number
        vZ:
          type: number
        module:
          type: number
        moduleXY:
          type: number
        v_eR:
          type: number
        v_eT:
          type: number
        r_dot:
          type: number
        theta_dot:
          type: number
        speedometer:
          type: number
    Acceleration:
      type: object
      description: "Aceleracion de un conductor"
      properties:
        aX:
          type: number
        aY:
          type: number
        aZ:
          type: number
        module:
          type: number
        moduleXY:
          type: number
        aTangential:
          type: number
        aNormal:
          type: number
        a_eR:
          type: number
        a_eT:
          type: number
        r_double_dot:
          type: number
        theta_double_dot:
          type: number
    Versors:
      type: object
      description: "Versores"
      properties:
        tangent:
          $ref: "#/components/schemas/TangentVersor"
        normal:
          $ref: "#/components/schemas/NormalVersor"

    TangentVersor:
      type: object
      description: "Versor tangente"
      properties:
        x:
          type: number
        y:
          type: number
    NormalVersor:
      type: object
      description: "Versor normal"
      properties:
        x:
          type: number
        y:
          type: number
