name: Create release on tag creation
on:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  Crear-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          npm install

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Create release files
        run: npm run build

      - name: get-package-version
        run: |
          $version = Get-Content -Raw -Path "./package.json" | ConvertFrom-Json | Select-Object -ExpandProperty version
          $projectName = Get-Content -Raw -Path "./package.json" | ConvertFrom-Json | Select-Object -ExpandProperty name
          echo version=$version >> "$Env:GITHUB_ENV"
          echo projectName=$projectName >> "$Env:GITHUB_ENV" 

      - name: Make release files
        run: |
          mkdir ../../release_files
          move win-unpacked ${{ github.event.repository.name }}
          move *.exe ../../release_files/
          7z a -tzip -mx=6 "../../release_files/$Env:projectName-$Env:version.zip" "${{ github.event.repository.name }}"
        working-directory: .\release\${{ env.version }}

      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: ${{ steps.tagName.outputs.tag }}
          files: |
            ./release_files/**

      - name: Cleanup
        run: |
          Remove-Item .\* -Recurse -Force